name: dev-env
on:
  push:
    branches:
      - dev
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/newbeerpongsakorn/bookinfo-ratings:dev

      # - run: docker build -t ghcr.io/newbeerpongsakorn/bookinfo-ratings:dev .
      # - run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      # - run: docker push ghcr.io/newbeerpongsakorn/bookinfo-ratings:dev
